#!/bin/bash

### This script is called after the user change environment variables in application setting page.
set -e
source "/var/apps/${TRIM_APPNAME}/cmd/common"

update_mgr_port() {
    # 设置管理服务端口
    cfg_mgr_address=$(get_yaml "${CFG_FILE}" "http.address")
    cfg_mgr_port="${cfg_mgr_address##*:}"
    if [[ "${cfg_mgr_port}" == "${adg_mgr_port}" ]]; then
        log_msg "管理服务端口未修改，保持不变: ${adg_mgr_port}"
    else
        if check_port_in_use "$adg_mgr_port" "AdGuardHome"; then
            log_msg "目标管理端口 $adg_mgr_port 已被占用"
            echo "管理端口 $adg_mgr_port 已被占用，请改用其他端口" > "${TRIM_TEMP_LOGFILE}"
            exit 1
        else
            log_msg "管理端口 $adg_mgr_port 未被占用"
        fi
        log_msg "设置管理服务端口: ${adg_mgr_port}"
        set_yaml "http.address" "0.0.0.0:${adg_mgr_port}" "${CFG_FILE}"
    fi
}

update_dns_port() {
    # 设置DNS服务端口
    cfg_dns_port=$(get_yaml "${CFG_FILE}" "dns.port")
    if [[ "${cfg_dns_port}" == "${adg_dns_port}" ]]; then
        log_msg "DNS服务端口未修改，保持不变: ${adg_dns_port}"
    else
        if check_port_in_use "$adg_dns_port" "AdGuardHome"; then
            log_msg "目标DNS端口 $adg_dns_port 已被占用"
            echo "DNS端口 $adg_dns_port 已被占用，请改用其他端口" > "${TRIM_TEMP_LOGFILE}"
            exit 1
        else
            log_msg "DNS端口 $adg_dns_port 未被占用"
        fi
        log_msg "设置DNS服务端口: ${adg_dns_port}"
        set_yaml "dns.port" "${adg_dns_port}" "${CFG_FILE}"
    fi
}

update_admin_password() {
    # 设置管理员密码
    password=$(encrypt_password "${adg_admin_password}")
    log_msg "设置管理员密码: ${adg_admin_password}"
    set_yaml "users[0].password" "${password}" "${CFG_FILE}"
}

update_logo() {
    # 设置Logo样式
    log_msg "开始设置Logo样式: ${adg_logo_name}"
    if [[ -z "${adg_logo_name}" ]]; then
        adg_logo_name="icon.png"
    fi
    bash -c "cp -f ${TRIM_APPDEST}/ui/logo_src/${adg_logo_name} ${TRIM_APPDEST}/ui/images/icon_64.png" >> ${LOG_FILE} 2>&1
    bash -c "cp -f ${TRIM_APPDEST}/ui/logo_src/${adg_logo_name} ${TRIM_APPDEST}/ui/images/icon_256.png" >> ${LOG_FILE} 2>&1
    bash -c "cp -f ${TRIM_APPDEST}/ui/logo_src/${adg_logo_name} /var/apps/${TRIM_APPNAME}/ICON.PNG" >> ${LOG_FILE} 2>&1
    bash -c "cp -f ${TRIM_APPDEST}/ui/logo_src/${adg_logo_name} /var/apps/${TRIM_APPNAME}/ICON_256.PNG" >> ${LOG_FILE} 2>&1
    log_msg "结束设置Logo样式: ${adg_logo_name}"
}

log_msg "config_callback脚本执行中..."
update_mgr_port
update_dns_port
update_admin_password
update_logo
install_version

exit 0