#!/bin/bash

### This script is called after the user uninstalls the application.

source "/var/apps/${TRIM_APPNAME}/cmd/common"

if [ "${adg_data_action}" == "delete" ]; then
    # log_msg "卸载时，用户选择清除数据"
    log_msg "开始清除数据"
    rm -rf "${TRIM_PKGVAR}"
    log_msg "开始清除数据"
    rm -rf "/vol1/@appshare/${TRIM_APPNAME}"
fi

exit 0